package io.mosip.test.residentTest.testcase;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import io.mosip.test.residentTest.utility.BaseClass;
import io.mosip.test.residentTest.utility.Commons;
import io.mosip.test.residentTest.utility.MockSMTPListener;

public class LoginTest extends BaseClass{
 
  @Test(priority = 0)
  public static void loginTest(WebDriver driver) throws Exception {
	  String envPath = System.getProperty("path");
	  String vid = System.getProperty("vid");
	  String otp = "111111";
	  
	
	 // password = System.getProperty("password");
	  String language = null;
    driver.get(envPath);
    driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
   // driver.findElement(By.linkText("Admin")).click();
    
//    try {
//		 language=Commons.getFieldData("langcode");
//	
//    System.out.println(language);
//    } catch (Exception e) {
//		// TODO Auto-generated catch block
//		e.printStackTrace();
//	}
    
    Commons.click(driver,By.xpath("//div[@id='dashboardCard1']"));
    Commons.click(driver,By.xpath("(//a[@href='#link1'])[2]"));
    Commons.click(driver,By.xpath("//button[text()='More Ways to Login']"));
    Commons.click(driver,By.xpath("//span[text()='Login with OTP']"));
   
    Commons.enter(driver, By.id("Otp_mosip-vid"), vid);
    Commons.switchToFrameByIndex(driver, 0);
    Commons.click(driver, By.xpath("//span[@id='recaptcha-anchor']"));
    driver.switchTo().parentFrame();
    Thread.sleep(3000);
    Commons.click(driver, By.xpath("//button[text()='Get OTP']")); 
   // otp = MockSMTPListener.getOtp(10, "ieptqaqwsshjdajcjlkessdfdtho.kctsencdisfjerafjmmshfygoqqg.1278@mailinator.com");
    System.out.println(otp);
    for(int i=0;i<=otp.length()-1;i++) {
    Commons.enter(driver, By.xpath("//*[@class=\"pincode-input-text\"]["+(i+1)+"]"), Character.toString(otp.charAt(i)));}
    Thread.sleep(4000);
    Commons.click(driver, By.xpath("//button[text()='Verify']"));
    Commons.click(driver, By.id("Manage-Identity-Data"));
    Commons.click(driver, By.id("Manage-VID"));
    Commons.click(driver, By.id("Manage-Authentication"));
    Commons.click(driver, By.id("Manage-Service-Requests"));
    Commons.click(driver, By.id("Manage-Credentials"));
    Commons.click(driver, By.id("birthdate"));
    Commons.click(driver, By.id("address"));
    Commons.click(driver, By.id("gender"));
    Commons.click(driver, By.xpath("//button[text()='Allow']"));
    Commons.click(driver, By.id("confirmmessagepopup"));
    
    
    
    
//    Commons.click(driver, By.xpath("(//mat-card[@class='mini-card mat-card'])[2]"));
//    Commons.click(driver, By.id("Perpetual"));
//    Commons.click(driver, By.id("confirmmessagepopup"));
//    Commons.click(driver, By.id("confirmmessagepopup"));
//    Commons.click(driver, By.id("Temporary"));
//    Commons.click(driver, By.id("confirmmessagepopup"));
//    Commons.click(driver, By.id("confirmmessagepopup"));    
//    Commons.click(driver, By.xpath("(//mat-icon[@id='delete0'])[2]"));
//    Commons.click(driver, By.xpath("//span[text()=' Delete ']"));
    
    
    
    
    
  }

public static void loginTest1(WebDriver driver) {
	// TODO Auto-generated method stub
	
}
}

