package io.mosip.test.residentTest.testcase;
import java.util.ArrayList;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.StaleElementReferenceException;
import org.openqa.selenium.TimeoutException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
// Generated by Selenium IDE
//import org.junit.Test;
//import org.junit.Before;
//import org.junit.After;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import com.aventstack.extentreports.Status;

import io.mosip.test.residentTest.utility.BaseClass;
import io.mosip.test.residentTest.utility.Commons;
import io.mosip.test.residentTest.utility.JsonUtil;
import io.mosip.test.residentTest.utility.MockSMTPListener;
import io.mosip.test.residentTest.utility.TestRunner;


 @Test(priority = 0)
public class LoginTest extends BaseClass{
 
	    @Test(priority = 0)
  public static void loginTest() throws Exception {
	    	//WebDriver driver = BaseClass.driver;
	  String envPath = System.getProperty("path");
	 // String vid = System.getProperty("vid");
	  String otp = "00000";
	  String externalemail=JsonUtil.JsonObjParsing(Commons.getTestData(),"externalemail");
	  test=extent.createTest("Login Test with valid Vid/UIN", "verify Login");
    driver.get(envPath);
    Thread.sleep(30000);
    driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
    Commons.click(test,driver,By.xpath("//div[@id='dashboardCard1']"));
    Commons.click(test,driver,By.xpath("(//a[@href='#link1'])[2]"));
    Commons.click(test,driver,By.xpath("//button[text()='More Ways to Login']"));
    Commons.click(test,driver,By.xpath("//span[text()='Login with OTP']"));
    Commons.enter(test,driver, By.id("Otp_mosip-vid"), TestRunner.perpetualVid);
    Commons.click(test,driver, By.xpath("//button[text()='Get OTP']")); 
    otp = MockSMTPListener.getOtp(10, externalemail);
    System.out.println(otp);
    for(int i=0;i<=otp.length()-1;i++) {
    Commons.enter(test,driver, By.xpath("//*[@class=\"pincode-input-text\"]["+(i+1)+"]"), Character.toString(otp.charAt(i)));}
    test.log(Status.INFO, "Extracted OTP");
    Thread.sleep(4000);
    
    Commons.click(test,driver, By.xpath("//button[text()='Verify']"));
    test.log(Status.INFO, "Click on Verify");
    List<WebElement> checkboxes = driver.findElements(By.xpath("//input[@type='checkbox']"));
    List<String> ids =new ArrayList<>();
    for(WebElement checkbox: checkboxes) {
    	String id = checkbox.getAttribute("id");	
    	ids.add(id);
    }
    System.out.println(ids);
    for(String id :ids) {
    WebElement checkbox= driver.findElement(By.id(id));
    js.executeScript("arguments[0].click();", checkbox); 
    }
    test.log(Status.INFO, "ALL Checkboxes are selected");
     Commons.click(test,driver, By.xpath("//button[text()='Allow']"));
     Commons.click(test,driver, By.id("confirmmessagepopup"));
  }
  

  
  


	    @Test(priority = 0) 
public static void loginTestWithTempraryVID() throws Exception {
	//WebDriver driver = BaseClass.driver;
String envPath = System.getProperty("path");
String vid = System.getProperty("vid");
String otp = "00000";
String externalemail=JsonUtil.JsonObjParsing(Commons.getTestData(),"externalemail");
String temporaryvid=JsonUtil.JsonObjParsing(Commons.getTestData(),"temporaryvid");
driver.get(envPath);
driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
test=extent.createTest("Login Test with valid Temprory Vid", "verify Login");
Commons.click(test,driver,By.xpath("//div[@id='dashboardCard1']"));
Commons.click(test,driver,By.xpath("(//a[@href='#link1'])[2]"));
Commons.click(test,driver,By.xpath("//button[text()='More Ways to Login']"));
Commons.click(test,driver,By.xpath("//span[text()='Login with OTP']"));
Commons.enter(test,driver, By.id("Otp_mosip-vid"), TestRunner.temporaryVid);
Commons.click(test,driver, By.xpath("//button[text()='Get OTP']")); 
otp = MockSMTPListener.getOtp(10, externalemail);
System.out.println(otp);
for(int i=0;i<=otp.length()-1;i++) {
Commons.enter(test,driver, By.xpath("//*[@class=\"pincode-input-text\"]["+(i+1)+"]"), Character.toString(otp.charAt(i)));}
test.log(Status.INFO, "Extracted OTP");
Thread.sleep(4000);
Commons.click(test,driver, By.xpath("//button[text()='Verify']"));
List<WebElement> checkboxes = driver.findElements(By.xpath("//input[@type='checkbox']"));
List<String> ids =new ArrayList<>();
for(WebElement checkbox: checkboxes) {
String id = checkbox.getAttribute("id");
ids.add(id);
}
System.out.println(ids);
for(String id :ids) {
WebElement checkbox= driver.findElement(By.id(id));
js.executeScript("arguments[0].click();", checkbox);
}
test.log(Status.INFO, "ALL Checkboxes are selected");
Commons.click(test,driver, By.xpath("//button[text()='Allow']"));
Commons.click(test,driver, By.id("confirmmessagepopup"));
Commons.click(test,driver, By.xpath("(//mat-card[@class='mini-card mat-card'])[2]"));
Commons.click(test,driver, By.xpath("(//mat-icon[@id='delete0'])[2]"));
Commons.click(test,driver, By.id("confirmmessagepopup"));
Commons.click(test,driver, By.id("confirmmessagepopup"));
//
}
//
//
//  
	    @Test
  public static void loginTestWithOneTimeVID() throws Exception {
		//WebDriver driver = BaseClass.driver;
	String envPath = System.getProperty("path");
	String vid = System.getProperty("vid");
	String otp = "00000";
	String externalemail=JsonUtil.JsonObjParsing(Commons.getTestData(),"externalemail");
	String onetimevid=JsonUtil.JsonObjParsing(Commons.getTestData(),"onetimevid");
	driver.get(envPath);
	driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
	test=extent.createTest("Login Test with valid OneTimeVid", "verify Login");
	Commons.click(test,driver,By.xpath("//div[@id='dashboardCard1']"));
	Commons.click(test,driver,By.xpath("(//a[@href='#link1'])[2]"));
	Commons.click(test,driver,By.xpath("//button[text()='More Ways to Login']"));
	Commons.click(test,driver,By.xpath("//span[text()='Login with OTP']"));
	Commons.enter(test,driver, By.id("Otp_mosip-vid"), TestRunner.onetimeuseVid);
	Commons.click(test,driver, By.xpath("//button[text()='Get OTP']")); 
	otp = MockSMTPListener.getOtp(10, externalemail);
	System.out.println(otp);
	for(int i=0;i<=otp.length()-1;i++) {
	Commons.enter(test,driver, By.xpath("//*[@class=\"pincode-input-text\"]["+(i+1)+"]"), Character.toString(otp.charAt(i)));}
	test.log(Status.INFO, "Extracted OTP");
	
	Thread.sleep(4000);
	Commons.click(test,driver, By.xpath("//button[text()='Verify']"));
	List<WebElement> checkboxes = driver.findElements(By.xpath("//input[@type='checkbox']"));
	List<String> ids =new ArrayList<>();
	for(WebElement checkbox: checkboxes) {
	String id = checkbox.getAttribute("id");
	ids.add(id);
	}
	System.out.println(ids);
	for(String id :ids) {
	WebElement checkbox= driver.findElement(By.id(id));
	js.executeScript("arguments[0].click();", checkbox);
	}
	test.log(Status.INFO, "ALL Checkboxes are selected");
	Commons.click(test,driver, By.xpath("//button[text()='Allow']"));
	Commons.click(test,driver, By.id("confirmmessagepopup"));
	Commons.click(test,driver, By.xpath("(//mat-card[@class='mini-card mat-card'])[2]"));
	Commons.click(test,driver, By.xpath("(//mat-icon[@id='delete0'])[3]"));
	Commons.click(test,driver, By.id("confirmmessagepopup"));
	Commons.click(test,driver, By.id("confirmmessagepopup")); 
	}
////  
//  
//   
//  @Test(priority = 0)
//  public static void loginTestWithUINRevokeVID() throws Exception {
//		//WebDriver driver = BaseClass.driver;
//	String envPath = System.getProperty("path");
//	String vid = System.getProperty("vid");
//	String otp = "00000";
//	String externalemail=JsonUtil.JsonObjParsing(Commons.getTestData(),"externalemail");
////	String UIN=JsonUtil.JsonObjParsing(Commons.getTestData(),"UIN");
//	driver.get(envPath);
//	driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
//	test=extent.createTest("Login Test with valid UIN to RevokeVid", "verify Login");
//	Commons.click(test,driver,By.xpath("//div[@id='dashboardCard1']"));
//	Commons.click(test,driver,By.xpath("(//a[@href='#link1'])[2]"));
//	Commons.click(test,driver,By.xpath("//button[text()='More Ways to Login']"));
//	Commons.click(test,driver,By.xpath("//span[text()='Login with OTP']"));
//	Commons.enter(test,driver, By.id("Otp_mosip-vid"), TestRunner.uin);
//	Commons.click(test,driver, By.xpath("//button[text()='Get OTP']")); 
//	otp = MockSMTPListener.getOtp(10, externalemail);
//	System.out.println(otp);
//	for(int i=0;i<=otp.length()-1;i++) {
//	Commons.enter(test,driver, By.xpath("//*[@class=\"pincode-input-text\"]["+(i+1)+"]"), Character.toString(otp.charAt(i)));}
//	test.log(Status.INFO, "Extracted OTP");
//	Thread.sleep(4000);
//	Commons.click(test,driver, By.xpath("//button[text()='Verify']"));
//	List<WebElement> checkboxes = driver.findElements(By.xpath("//input[@type='checkbox']"));
//	List<String> ids =new ArrayList<>();
//	for(WebElement checkbox: checkboxes) {
//	String id = checkbox.getAttribute("id");
//	ids.add(id);
//	}
//	System.out.println(ids);
//	for(String id :ids) {
//	WebElement checkbox= driver.findElement(By.id(id));
//	js.executeScript("arguments[0].click();", checkbox);
//	}
//	 test.log(Status.INFO, "ALL Checkboxes are selected");
//	Commons.click(test,driver, By.xpath("//button[text()='Allow']"));
//	Commons.click(test,driver, By.id("confirmmessagepopup"));
//	Commons.click(test,driver, By.xpath("(//mat-card[@class='mini-card mat-card'])[2]"));
//	Commons.click(test,driver, By.xpath("(//mat-icon[@id='delete0'])[1]"));
//	Commons.click(test,driver, By.id("confirmmessagepopup"));
//	
//	Commons.click(test,driver, By.id("confirmmessagepopup")); 
//	}
//  
//  
//  @Test(priority = 0)
//  public static void loginTestWithUINCreatVID() throws Exception {
//		//WebDriver driver = BaseClass.driver;
//	String envPath = System.getProperty("path");
//	String vid = System.getProperty("vid");
//	String otp = "00000";
//	String externalemail=JsonUtil.JsonObjParsing(Commons.getTestData(),"externalemail");
////	String UIN=JsonUtil.JsonObjParsing(Commons.getTestData(),"UIN");
//	driver.get(envPath);
//	driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
//	test=extent.createTest("Login Test with valid UIN to Create Vid", "verify Login");
//	Commons.click(test,driver,By.xpath("//div[@id='dashboardCard1']"));
//	Commons.click(test,driver,By.xpath("(//a[@href='#link1'])[2]"));
//	Commons.click(test,driver,By.xpath("//button[text()='More Ways to Login']"));
//	Commons.click(test,driver,By.xpath("//span[text()='Login with OTP']"));
//	Commons.enter(test,driver, By.id("Otp_mosip-vid"), TestRunner.uin);
//	Commons.click(test,driver, By.xpath("//button[text()='Get OTP']")); 
//	otp = MockSMTPListener.getOtp(10, externalemail);
//	System.out.println(otp);
//	for(int i=0;i<=otp.length()-1;i++) {
//	Commons.enter(test,driver, By.xpath("//*[@class=\"pincode-input-text\"]["+(i+1)+"]"), Character.toString(otp.charAt(i)));}
//	test.log(Status.INFO, "Extracted OTP");
//	Thread.sleep(4000);
//	Commons.click(test,driver, By.xpath("//button[text()='Verify']"));
//	List<WebElement> checkboxes = driver.findElements(By.xpath("//input[@type='checkbox']"));
//	List<String> ids =new ArrayList<>();
//	for(WebElement checkbox: checkboxes) {
//	String id = checkbox.getAttribute("id");
//	ids.add(id);
//	}
//	System.out.println(ids);
//	for(String id :ids) {
//	WebElement checkbox= driver.findElement(By.id(id));
//	js.executeScript("arguments[0].click();", checkbox);
//	}
//	 test.log(Status.INFO, "ALL Checkboxes are selected");
//	Commons.click(test,driver, By.xpath("//button[text()='Allow']"));
//	Commons.click(test,driver, By.id("confirmmessagepopup"));
//	Commons.click(test,driver, By.xpath("(//mat-card[@class='mini-card mat-card'])[2]"));
//	Commons.click(test,driver, By.id("Perpetual"));
//	
//	Commons.click(test,driver, By.id("confirmmessagepopup"));
//	Commons.click(test,driver, By.id("confirmmessagepopup")); 
//	}
//
//  
//  
//  public static void loginTestWithVidRevokeVid() throws Exception {
//		//WebDriver driver = BaseClass.driver;
//	String envPath = System.getProperty("path");
//	String otp = "00000";
//	String externalemail=JsonUtil.JsonObjParsing(Commons.getTestData(),"externalemail");
//	String perpetualvid=JsonUtil.JsonObjParsing(Commons.getTestData(),"perpetualvid");
//	driver.get(envPath);
//	driver.manage().timeouts().implicitlyWait(20, TimeUnit.SECONDS);
//	test=extent.createTest("Login Test with valid Vid to Revoke same vid", "verify Login");
//	Commons.click(test,driver,By.xpath("//div[@id='dashboardCard1']"));
//	Commons.click(test,driver,By.xpath("(//a[@href='#link1'])[2]"));
//	Commons.click(test,driver,By.xpath("//button[text()='More Ways to Login']"));
//	Commons.click(test,driver,By.xpath("//span[text()='Login with OTP']"));
//	Commons.enter(test,driver, By.id("Otp_mosip-vid"), TestRunner.perpetualVid);
//	Commons.click(test,driver, By.xpath("//button[text()='Get OTP']")); 
//	otp = MockSMTPListener.getOtp(10, externalemail);
//	System.out.println(otp);
//	for(int i=0;i<=otp.length()-1;i++) {
//	Commons.enter(test,driver, By.xpath("//*[@class=\"pincode-input-text\"]["+(i+1)+"]"), Character.toString(otp.charAt(i)));}
//	test.log(Status.INFO, "Extracted OTP");
//	Thread.sleep(4000);
//	Commons.click(test,driver, By.xpath("//button[text()='Verify']"));
//	List<WebElement> checkboxes = driver.findElements(By.xpath("//input[@type='checkbox']"));
//	List<String> ids =new ArrayList<>();
//	for(WebElement checkbox: checkboxes) {
//	String id = checkbox.getAttribute("id");
//	ids.add(id);
//	}
//	System.out.println(ids);
//	for(String id :ids) {
//	WebElement checkbox= driver.findElement(By.id(id));
//	js.executeScript("arguments[0].click();", checkbox);
//	}
//	 test.log(Status.INFO, "ALL Checkboxes are selected");
//	Commons.click(test,driver, By.xpath("//button[text()='Allow']"));
//	Commons.click(test,driver, By.id("confirmmessagepopup"));
//	Commons.click(test,driver, By.xpath("(//mat-card[@class='mini-card mat-card'])[2]"));
//	Commons.click(test,driver, By.xpath("(//mat-icon[@id='delete0'])[1]"));
//	Commons.click(test,driver, By.id("confirmmessagepopup"));
//	Commons.click(test,driver, By.id("confirmmessagepopup")); 
//	
//	}
  


}